[package]
name = "cw-dao-voting-cw20-balance"
authors = ["ekez <ekez@withoutdoing.com>"]
description = "A DAO DAO voting module that determines voting power based on the cw20 balance of an address. This should never, ever be used outside of testing code. If you break the rules and use it for a real DAO you'll get instantly rekt."
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-storage = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw-utils = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cw-dao-core-macros = { workspace = true }
cw-dao-core-interface = { workspace = true }
cw20-base = { workspace = true }

[dev-dependencies]
cosmwasm-schema = { workspace = true }
cw-multi-test = { workspace = true }
