[package]
name = "proposal-hooks"
description = "A package for managing hooks which fire when proposals have their status change."
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
schemars = { workspace = true }
serde = { workspace = true }
cosmwasm-std = { workspace = true }
indexable-hooks = { workspace = true }
voting = { workspace = true }