[workspace]
exclude = []
members = [
  "packages/dao-interface",
  "packages/cw-orch",
  "packages/dao-voting",
  "packages/dao-pre-propose-base",
  "packages/cw-paginate-storage",
  "packages/dao-dao-macros",
  "packages/cw-hooks",
  "packages/cw-denom",
  "packages/dao-hooks",
  "contracts/proposal/dao-proposal-single",
  "contracts/pre-propose/dao-pre-propose-single",
  "contracts/voting/dao-voting-cw4",
  "contracts/test/dao-proposal-sudo",
  "contracts/dao-dao-core",
]

resolver = "2"

[workspace.package]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/DA0-DA0/dao-contracts"
version = "2.7.0"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
panic = 'abort'
rpath = false
# Please do not disable these. Doing so will cause overflow checks in
# all workspace members to stop working. Overflows should be errors.
overflow-checks = true

[workspace.dependencies]
anyhow = { version = "1.0" }
assert_matches = "1.5"
bech32 = "0.11.0"
cosm-orc = { version = "4.0" }
cosm-tome = "0.2"
cosmos-sdk-proto = { version = "0.27.0", features = ['serde'] }
cosmwasm-schema = { version = "2.2.2" }
cosmwasm-std = { version = "2.2.2", features = ["cosmwasm_2_2"] }
cw-controllers = "2.0.0"
cw-multi-test = { version = "2.4.0", features = ["cosmwasm_2_2"] }
cw-storage-plus = { version = "2.0.0" }
cw-utils = "2.0.0"
cw2 = "2.0.0"
cw20 = "2.0.0"
cw20-base = "2.0.0"
cw3 = "2.0.0"
cw4 = "2.0.0"
cw4-group = "2.0.0"
env_logger = "0.11.8"
once_cell = "1.18"
omniflix-std = "0.1.8"
proc-macro2 = "1.0"
prost = { version = "0.13.5", features = ["prost-derive"] }
prost-types = { version = "0.13.5", default-features = false }
prost-derive = "0.13.5"
quote = "1.0"
rand = "0.9.1"
schemars = "0.8"
semver = "1.0.20"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-cw-value = "0.7"
serde_json = "1.0"
serde_yaml = "0.9"
sg-multi-test = "3.1.0"
sg-std = "3.1.0"
sg721 = "3.1.0"
sg721-base = "3.1.0"
syn = { version = "1.0", features = ["derive"] }
test-context = "0.4.1"
thiserror = { version = "2.0.12" }
wynd-utils = "0.4"
cw-orch = "0.28.0"
tokio = "1.40.0"

cw-ownable = "2.1.0"

# cw-nfts
cw721 = { git = "https://github.com/public-awesome/cw-nfts" }
cw721-base = { git = "https://github.com/public-awesome/cw-nfts" }

dao-interface = { path = "./packages/dao-interface" }
dao-cw-orch = { path = "./packages/cw-orch" }
dao-proposal-single = { path = "./contracts/proposal/dao-proposal-single" }
dao-pre-propose-single = { path = "./contracts/pre-propose/dao-pre-propose-single" }
dao-voting = { path = "./packages/dao-voting" }
dao-voting-cw4 = { path = "./contracts/voting/dao-voting-cw4" }
dao-proposal-sudo = { path = "./contracts/test/dao-proposal-sudo" }
dao-pre-propose-base = { path = "./packages/dao-pre-propose-base" }
dao-dao-core = { path = "./contracts/dao-dao-core" }
cw-paginate-storage = { path = "./packages/cw-paginate-storage" }
dao-dao-macros = { path = "./packages/dao-dao-macros" }
cw-hooks = { path = "./packages/cw-hooks" }
cw-denom = { path = "./packages/cw-denom" }
dao-hooks = { path = "./packages/dao-hooks" }
