[package]
name = "cw-dao-vote-hooks"
description = "A package for managing hooks which fire when votes are cast."
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
schemars = { workspace = true }
serde = { workspace = true }
cosmwasm-std = { workspace = true }
cw-indexable-hooks = { workspace = true }
cw-dao-voting = { workspace = true }
