[package]
name = "cwd-vote-hooks"
version = "0.2.0"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package for managing vote hooks."

[dependencies]
cosmwasm-std = "1.1"
cosmwasm-schema = "1.1"
cwd-hooks = { path = "../cwd-hooks" }
cwd-voting = { version = "0.2.0", path = "../cwd-voting" }