[package]
name = "cwd-proposal-hooks"
version = "0.2.0"
edition = "2021"
authors = ["Callum Anderson <callumanderson745@gmail.com>"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package for managing proposal hooks."

[dependencies]
cosmwasm-std = "1.1"
cosmwasm-schema = "1.1"
cwd-hooks = { path = "../cwd-hooks" }
cwd-voting = { path = "../cwd-voting" }