[package]
name = "cwd-pre-propose-multiple"
version = "0.2.0"
authors = ["ekez <zekemedley@gmail.com>", "Jake Hartnell <meow@no-reply.com>", "blue-note"]
edition = "2021"
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A DAO DAO pre-propose module for cwd-proposal-multiple for native and cw20 deposits."

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std.workspace = true
cosmwasm-schema.workspace = true
cw2.workspace = true
cwd-pre-propose-base = { version = "*", path = "../../../packages/cwd-pre-propose-base" }
cwd-voting = { path = "../../../packages/cwd-voting" }

[dev-dependencies]
cw-multi-test.workspace = true
cw-utils.workspace = true
cw4-group.workspace = true
cw20.workspace = true
cw20-base.workspace = true
cwd-voting-cw20-staked = { path = "../../voting/cwd-voting-cw20-staked" }
cwd-proposal-multiple = { path = "../../proposal/cwd-proposal-multiple" }
cwd-core = { path = "../../cwd-core" }
cwd-voting-cw4 = { path = "../../voting/cwd-voting-cw4" }
cwd-voting = { path = "../../../packages/cwd-voting" }
cw-denom = { path = "../../../packages/cw-denom" }
cwd-interface = { path = "../../../packages/cwd-interface" }
cwd-testing = { path = "../../../packages/cwd-testing" }
cwd-proposal-hooks = { path = "../../../packages/cwd-proposal-hooks" }