[package]
name = "cw-dao-core-interface"
description = "Types used for interfacing with cw-dao-core."
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cw-dao-core-macros = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
cw2 = { workspace = true }

[dev-dependencies]
cosmwasm-schema = { workspace = true }
