[package]
name = "testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.0.0-beta5" }
voting = { path = "../voting", version = "*" }
cw-multi-test = {  version = "0.13" }
rand = "0.8"