[package]
name = "cwd-voting-cw721-staked"
version = "0.2.0"
authors = ["CypherApe cypherape@protonmail.com"]
edition = "2021"
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A DAO DAO voting module based on staked cw721 tokens."

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std.workspace = true
cosmwasm-schema.workspace = true
cw-storage-plus.workspace = true
cw-controllers.workspace = true
cwd-macros = { path = "../../../packages/cwd-macros" }
cwd-interface = { path = "../../../packages/cwd-interface" }
cw721-controllers = { path = "../../../packages/cw721-controllers" }
cw-paginate = { path = "../../../packages/cw-paginate" }
cw721.workspace = true
cw-utils.workspace = true
cw2.workspace = true
thiserror.workspace = true
indexmap = { workspace = true, features = ["serde"] }

[dev-dependencies]
cw721-base.workspace = true
cw-multi-test.workspace = true
anyhow.workspace = true
