[package]
name = "cwd-macros"
version = "0.2.0"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package macros for deriving DAO module interfaces."

[lib]
proc-macro = true
[dependencies]
cosmwasm-schema = { version = "1.1" }
syn = { version = "1.0", features = ["derive"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
cwd-interface = { path = "../cwd-interface"}
cosmwasm-std = { version = "1.1" }

