[package]
name = "scripts"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
cw-orch = { workspace = true, features = ["daemon"] }
dao-cw-orch = { git = "https://github.com/hard-nett/dao-contracts", branch = "feat/external-cw-orch" }

# scripts specific
dotenv = { version = "0.15.0" }
pretty_env_logger = { version = "0.5.0" }

# cw-orch enabled DAO DAO deps
[dev-dependencies]
dao-interface-master = { package = "dao-interface", git = "https://github.com/DA0-DA0/dao-contracts", branch = "main" }
dao-proposal-sudo = { git = "https://github.com/Kayanski/dao-contracts", branch = "development", features = [
    "library",
] }
dao-proposal-single = { git = "https://github.com/Kayanski/dao-contracts", branch = "development", features = [
    "library",
] }

dao-interface           = { git = "https://github.com/hard-nett/dao-contracts", branch = "feat/external-cw-orch" }
dao-voting              = { git = "https://github.com/hard-nett/dao-contracts", branch = "feat/external-cw-orch" }
cw-payroll-factory      = { git = "https://github.com/hard-nett/dao-contracts", branch = "feat/external-cw-orch" }
cw-token-swap           = { git = "https://github.com/hard-nett/dao-contracts", branch = "feat/external-cw-orch" }
cw-admin-factory        = { git = "https://github.com/hard-nett/dao-contracts", branch = "feat/external-cw-orch" }
cw-tokenfactory-issuer  = { git = "https://github.com/hard-nett/dao-contracts", branch = "feat/external-cw-orch" }
cw-vesting              = { git = "https://github.com/hard-nett/dao-contracts", branch = "feat/external-cw-orch" }
cw721-roles             = { git = "https://github.com/hard-nett/dao-contracts", branch = "feat/external-cw-orch" }
dao-migrator            = { git = "https://github.com/hard-nett/dao-contracts", branch = "feat/external-cw-orch" }