[package]
name = "scripts"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
cw-orch = { workspace = true, features = ["daemon"] }
dao-cw-orch = { path = "../packages/cw-orch", version = "2.5.0" }
# scripts specific
dotenv = { version = "0.15.0" }
pretty_env_logger = { version = "0.5.0" }

# cw-orch enabled DAO DAO deps
[dev-dependencies]
dao-proposal-sudo = { workspace = true, features = ["library"] }
dao-proposal-single = { workspace = true, features = ["library"] }
dao-interface = { workspace = true }
dao-voting = { workspace = true }
cw-payroll-factory = { workspace = true }
cw-token-swap = { workspace = true }
cw-admin-factory = { workspace = true }
cw-tokenfactory-issuer = { workspace = true }
cw-vesting = { workspace = true }
cw721-roles = { workspace = true }
dao-migrator = { workspace = true }
btsg-ft-factory = { workspace = true }
