[package]
name = "cw-dao-proposal-testing"
description = "A package for testing DAO DAO proposal modules."
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

# This crate depends on multi-test and rand. These are not features in
# wasm builds of cosmwasm. Despite this crate only being used as a dev
# dependency, because it is part of the workspace it will always be
# compiled. There is no good way to remove a member from a workspace
# conditionally. As such, we don't compile anything here if we're
# targeting wasm.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = "0.8"
cosmwasm-std = { workspace = true }
cw-dao-voting = { workspace = true }
cw-multi-test = {  workspace = true }
cw20-base = { workspace = true }
cw4 = { workspace = true }
cw4-group = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw20-stake = { workspace = true }
cw-dao-voting-cw4 = { workspace = true }
cw-dao-voting-cw20-balance = { workspace = true }
cw-dao-voting-staked-cw20 = { workspace = true }
cw-indexable-hooks = { workspace = true }
cw-dao-core = { workspace = true }
cosmwasm-schema = { version = "1.0.0" }
cw-dao-core-interface = { workspace = true }
