[package]
name = "cw721-controllers"
authors = ["CypherApe cypherape@protonmail.com"]
description = "Common cw721 controllers we can reuse in many contracts."
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cw-utils = { workspace = true }
cw-storage-plus = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
