[package]
name = "cwd-interface"
version = "0.2.0"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package containing interface definitions for DAO DAO DAOs."

[dependencies]
cosmwasm-std = { version = "1.1" }
cosmwasm-schema = "1.1"
cwd-macros = { path = "../cwd-macros" }

cw2 = "0.15"

[dev-dependencies]
cosmwasm-schema = { version = "1.1" }
