[package]
name = "cw-indexable-hooks" 
description = "A package for managing a list of hook receivers for a CosmWasm contract."
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
